name: Deploy to demo server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    workflows: [ "Build" ]  # This matches the name from the first workflow
    types:
      - completed  # Trigger when the build workflow completes

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          ls -lha ~/.ssh
          echo "${{ secrets.SSH_PRIV_ARES }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 1989 ares.swipetor.com >> ~/.ssh/known_hosts

      - name: Trigger pull-deploy
        run: |
          ssh -p1989 ata@ares.swipetor.com "/opt/swipetor/bin/pull-deploy/run.sh"
